rharter/auto-value-gson

- README.md
`registerTypeAdapterFactory` only takes one param according to [Gson Javadocs](http://google.github.io/gson/apidocs/).
> Remove param Foo.class from registerTypeAdapterFactory

- src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
Use primitive types when possible.  This fixes NullPointerExceptions when properties that are primitive types are not in the supplied json
> Use primitive types

- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
This pull request fixes a TypeAdapter generation for cases when annotated class has a char field.
At the moment incuding `char` field results in generation of TypeAdapter that fails to compile.
To reproduce:
```java
@AutoValue
public abstract class Test {
public abstract char c();
public static TypeAdapter<Test> typeAdapter(Gson gson) {
return new AutoValue_Test.GsonTypeAdapter(gson);
}
}
```
Above code will result in generation of `TypeAdapter.read()` which fails to compile.
What happens is that `auto-value-gson` will use Guava's `Defaults.getDefault(char.class)`, which returns `\0`, then apply `.toString()` to it and write it **unquoted** as `char c = \0`, which will break the compilation.
This PR wraps `\0` in single quotes which fixes the issue.
> Fix generation of TypeAdapter.read() for 'char' values

- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java
- auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java
- example/src/main/java/com/ryanharter/auto/value/gson/example/Address.java
- example/src/main/java/com/ryanharter/auto/value/gson/example/Person.java
- example/src/test/java/com/ryanharter/auto/value/gson/example/PersonTest.java
Hi, I am using this framework and it's great!
I have found a small problem in AutoValueGsonTypeAdapterFactory. Sometimes, for example in nested objects, the second parameter of `AutoValueGsonTypeAdapterFactory.create` contains the generated class and not the original one. I have changed the check from `rawType.equals(Person.class)` to `Person.class.isAssignableFrom(rawType)` to fix it.
I updated the example to add a nested object `Address` with a `SerializedName` annotated field, with the equals check it doesn't work (the autogenerated `TypeAdapter<Address>` is not used).
> Replaced equals check with isAssignableFrom in  AutoValueGsonTypeAdapterFactory

- README.md
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/GsonTypeAdapterFactory.java
- auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java
- example/build.gradle
- example/src/main/java/com/ryanharter/auto/value/gson/example/SampleAdapterFactory.java
- example/src/test/java/com/ryanharter/auto/value/gson/example/PersonTest.java
- gradle.properties
Followup from https://github.com/rharter/auto-value-moshi/pull/47 and resolves #52 and resolves #58. 
(copying over from https://github.com/rharter/auto-value-moshi/pull/47)
This would be a breaking change, but for the better I think as it'd be a bit muddled to try to maintain the old behavior and this one's as well.
Now, people would have to declare their own @GsonTypeAdapterFactory class(es) to specify where they want it generated.
```java
@GsonTypeAdapterFactory
public abstract class MyAdapterFactory implements TypeAdapterFactory {
// Static factory method to access the package
// private generated implementation
public static TypeAdapterFactory create() {
return new AutoValueGson_MyAdapterFactory();
}
}
```
> Switch to autovalue-esque style of generating Factories

- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
If `JsonToken.NULL` declared any instance members, `getClass()` would return
a synthetic subclass of `JsonToken.class`.
This fixes an Error Prone warning: http://errorprone.info/bugpattern/GetClassOnEnum
> Use getDeclaredClass() instead of getClass() on enums

- README.md
The current readme uses `.defaultQuux()`, but the code that is actually generated uses the form  `.setDefaultQuux()`. Also, for fields that include underscores, it looks like `.setDefaultWith_underscore()`.
> Fixed README.md to make it more accurate

- auto-value-gson/build.gradle
It's only needed at compile time to generate the service file.
> set auto-service dependency to compileOnly

- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
I found these while writing an ErrorProne check to identify bad invocations of CodeBlock formatting. I don't know the context of this code, but it seems that the 2nd and 3rd parameters are unused.
> Remove unused arguments to CodeBlock.of()

- README.md
- auto-value-gson-annotations/src/main/java/com/ryanharter/auto/value/gson/GenerateTypeAdapter.java
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- example/build.gradle
- example/src/main/java/com/ryanharter/auto/value/gson/example/WebResponse.java
- example/src/main/java/com/ryanharter/auto/value/gson/example/WebResponseNoStatic.java
- example/src/test/java/com/ryanharter/auto/value/gson/example/WebResponseTest.java
This implemented support for `@GenerateTypeAdapter`, which is an annotation that can be used to indicate that the developer wants the generated typeadapater to be generated as a top-level class in the same package. This also includes a runtime reflective typeadapterfactory (loosely based on Jake's AutoGson + Butter Knife's lookup logic).
What this means is that you can now trigger generation with this annotation OR a static TypeAdapter-returning method.
You can use both a static method and the annotation, but if you do, the static method implementation will need to point to the public top-level class.
If the annotation is present, no intermediary AutoValue class will be generated either.
The adapter lookups are cached similar to how Butter Knife's bindings are cached.
The runtime factory …
> Implement @GenerateTypeAdapter support

- auto-value-gson-annotations/src/main/java/com/ryanharter/auto/value/gson/GenerateTypeAdapter.java
parameterCount is a java 8 API. Perhaps as a sign of the times, no one's reported it yet and I never ran into it in testing. A little annoyed my IDE didn't lint it either though
> Fix usage of java 8 API in GenerateTypeAdapter

- auto-value-gson-annotations/src/main/java/com/ryanharter/auto/value/gson/GenerateTypeAdapter.java
ConcurrentHashMap bugs on some versions of android: https://code.google.com/p/android/issues/detail?id=170073
> Switch from ConcurrentHashMap to Collections.synchronizedMap() in GenerateTypeAdapter

- auto-value-gson/build.gradle
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
Fixes usage of auto-value-gson with JDK 9 and newer.
This bumps the dependency of auto-common to 0.9, because this version includes the necessary utility method.
> #164 Use correct "Generated"-annotation based on JDK version.

- auto-value-gson-annotations/src/main/java/com/ryanharter/auto/value/gson/Ignore.java
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
Relates to #48, but I can't repro any issue described there and think it may just be old. This improves it a bit by not always inverting the serialization checks.
I do plan to just use a shared transient annotation library for this in a separate PR, but this should make switching to that easy
> Clean up Ignore logic a bit

- README.md
- auto-value-gson-runtime/src/main/resources/META-INF/proguard/autovaluegson.pro
This embeds proguard rules directly in the jar for R8/proguard, and also tunes them to use newer features to only selectively keep adapters (adapted from Moshi's configuration)
Resolves #200
> Embed proguard rules

- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- example/src/main/java/com/ryanharter/auto/value/gson/example/GenericsExample.java
Fixes #226.
Invalid java code was being generated when trying to instantiate a builder with generics via its factory method inside the `TypeAdapter#read`.
The fix is to use the builder's type rather than class when declaring the builder field inside of `TypeAdapter#read`.
I've also updated `GenericsExample` to show that it works and to serve as a test. The read method generated now looks like.
```java
public GenericsExample<A, B, C> read(JsonReader jsonReader) throws IOException {
if (jsonReader.peek() == JsonToken.NULL) {
jsonReader.nextNull();
return null;
}
jsonReader.beginObject();
GenericsExample.Builder<A, B, C> builder = GenericsExample.builder();
...
}
```
> Fix factory method with generics

- auto-value-gson-runtime/src/main/java/com/ryanharter/auto/value/gson/GenerateTypeAdapter.java
- auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- example/build.gradle
- example/src/test/java/com/ryanharter/auto/value/gson/example/GenerateTypeAdapterTest.java
This allows for reuse of adapters as well as a faster traversal rather than the reflective fall-through. Before - it would try the whole constructor lookup before trying to walk up to the superclass as a stop-gap and also potentially create duplicate adapters in Moshi's cache.
This also revealed in testing that GenerateTypeAdapter didn't support nested types, which are fixed opportunistically here using Moshi's naming scheme.
> Optimize hierarchy lookups for GenerateTypeAdapter

- auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
Wasn't actually an issue in practice since none of the types we pass into this are nested types, but good hygiene
> Use reflection name in proguardNameOf()

- README.md
Hi,
I noticed the runtime FACTORY example was not using the latest GsonBuilder API.
Cheers
> Update an example in README with most recent API

- auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- auto-value-gson-extension/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
Currently we only recognize it when it is applied to a getter method.
This change recognizes it when it is applied to the return type of a getter.
AutoValueExtension should probably include a helper method to do this.
> Recognize `@Nullable` as a `TYPE_USE` annotation.

- auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
- auto-value-gson-extension/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
AutoValue has a number of ways to set a property with a method whose parameter
does not exactly match the return type of the property method. For example, a
property defined by `abstract ImmutableList<String> getFoo()` can be set by an
abstract method `abstract Builder setFoo(List<String>)`. AutoValue knows how
to implement this by calling `ImmutableList.copyOf`. Here, we don't need to know
about `ImmutableList.copyOf`, we just need to know that this setter is indeed
callable to set the value of the list. There are similar considerations for
list builders (`ImmutableList.Builder<String> fooBuilder()`) and for `Optional`
(`Optional<String>` set by plain `String`). This change allows auto-value-gson
to use these alternative ways of setting a property, rather than requiring that
the setter …
> Generalize support for setting properties with builders.
