README.md, build.gradle, src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java, src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
This allows you to only generate TypeAdapters for applicable classes.
=> Adds requirement of public static method returning TypeAdapter<Foo> to apply the extension.

src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java, src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
=> Fixes issue causing failure with non-standard class/package names.

README.md, auto-value-gson/build.gradle, auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java, auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java
=> Adds type adapter factory for all generated type adapters.

auto-value-gson/build.gradle, auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java
=> Updates extension to use AutoValue 1.3-rc1

auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java, auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/GsonTypeAdapter.java, auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
=> Add support for custom field adapters

.travis.yml, README.md, auto-value-gson/build.gradle, auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java, auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
=> Serialize collections to null by default, add compiler option to serialize to empty variants

example/src/main/java/com/ryanharter/auto/value/gson/example/BirthdateAdapter.java, example/src/main/java/com/ryanharter/auto/value/gson/example/Person.java, example/src/test/java/com/ryanharter/auto/value/gson/example/PersonTest.java
Add sample for custom @GsonTypeAdapter annotation
=> Update sample with  @GsonTypeAdapter

CHANGELOG.md
Update release date typo in CHANGELOG.md
=> Update release date typo

README.md
Adds missing documentation on how to enable mutable TypeAdapters.
=> Update README to include mutable adapter flag.

auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java, auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java
I guess the problem was on how AutoValueGson was generating the class name, I checked how AutoValue generates the class name[1] and came up with this solution, hope that you'd like it, if not then I'm all ears for improvements. 
Also If you'd like, I could add an example code too in the 'example' project.
[1] https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L216
=> Fixes #110 - Support inner Factory class generation

auto-value-gson-annotations/build.gradle
=> Make annotations java 7 compatible

auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java, auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java
We generate the TypeAdapterFactories by sorting the adapters
alphabetically.
Issue: 182
=> Deterministic generation of TypeAdapterFactories

auto-value-gson/build.gradle
Resolves #190
Also adds an explicit guava dependency rather than counting on it coming through auto-common
=> Shade autocommon and guava

auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessor.java, auto-value-gson/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonAdapterFactoryProcessorTest.java
This resolves a couple issues around missing error reporting for two cases:
1 - No AutoValue models found
2 - AutoValue models found, but none have a static `typeAdapter` method
Resolves #171
Resolves #170
While reported as different issues, I'm fairly certain they're the same issue. The two tests I added would only repro #170, but that was also because some of the way the logic on master was set up, it would basically just quietly refuse to generate the factory rather than error during generation. The logic changes here to record factory counts early account for that as well
=> Report errors eagerly for missing (applicable) AutoValue models in factory generation

auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java, example/src/main/java/com/ryanharter/auto/value/gson/example/Address.java, example/src/main/java/com/ryanharter/auto/value/gson/example/wildgenerics/AddressGenericBase.java, example/src/main/java/com/ryanharter/auto/value/gson/example/wildgenerics/DoubleGeneric.java, example/src/main/java/com/ryanharter/auto/value/gson/example/wildgenerics/GenericBase.java, example/src/test/java/com/ryanharter/auto/value/gson/example/wildgenerics/WildGenericsTest.java
Resolves #240 using the methodology described there.
=> Resolve materialized types in subclasses of generic types

CHANGELOG.md
Fix the section name to aid discoverability,
and link to it.
=> Fix the section name:

auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/ProguardConfig.java, auto-value-gson-extension/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
Proguard speaks reflection names
=> Fix generated proguard names for inner classes

auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java
fix https://github.com/rharter/auto-value-gson/issues/252
=> fix read method for builder pattern

auto-value-gson-factory/src/main/java/com/ryanharter/auto/value/gson/factory/AutoValueGsonAdapterFactoryProcessor.java
=> use canonical class name for sorting elements

auto-value-gson-extension/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java, auto-value-gson-extension/src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java
Previously if you had a property of type `Map.@Nullable Entry`
then it would end up in the generated source code as
`@Nullable Map.Entry`, which doesn't compile.
Fixes #261.
=> Fix `TYPE_USE` annotations on nested types.
